INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 0, 'system', CURRENT_TIMESTAMP, 'a3q0dxzOk0cmqI3xaYFwtS5a4jENAjID', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 1, 'system', CURRENT_TIMESTAMP, 'zztqcO5Ici8TwfmtCymT5XNjRZ5uzcDs', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 2, 'system', CURRENT_TIMESTAMP, 'k086oNsQ51tBon8YV7KohoUlEExDYTEi', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 3, 'system', CURRENT_TIMESTAMP, 'nbgOvUwh8wr3drNc6eyfzutLsISzdfSB', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 4, 'system', CURRENT_TIMESTAMP, 'OmUd0hXH4RGeFn0cb0sE6LuxkejiAHUZ', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 5, 'system', CURRENT_TIMESTAMP, 'l3c0pP1zzvIjpybzdgLJU2nXm66dftqV', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 6, 'system', CURRENT_TIMESTAMP, 'MSAQNBVkaj9LCBG7YehnQn3IPp5oMNn1', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 7, 'system', CURRENT_TIMESTAMP, 'q3gVwlbZ0HarDdb9oH4MDUdq4fawgoAq', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 8, 'system', CURRENT_TIMESTAMP, 'atbRhus5NKQw1YYaPXwQXHtsK9wnV7fg', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 9, 'system', CURRENT_TIMESTAMP, 'lcJsFTqLByOCVNCaPP2xZrocCzDSTpd1', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 10, 'system', CURRENT_TIMESTAMP, 'E6qlivBXbfpI8omCMDl8RSY1Jf9VTsUP', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 11, 'system', CURRENT_TIMESTAMP, 'kXcJXnoTFTz7Z68dEm5BveOVX2gumDUj', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 12, 'system', CURRENT_TIMESTAMP, 'jp9KW3qGniWPFZ2vVmLdjUpna7IFviEg', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 13, 'system', CURRENT_TIMESTAMP, 'MkvZneEPiHAevvEIm8Ghrx3w4bROaB6u', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 14, 'system', CURRENT_TIMESTAMP, 'qdPNtEJ74cO9drfv1vlmUR3rhWUANNpb', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 0, 15, 'system', CURRENT_TIMESTAMP, 'CgDniX89lhsoAVRSkDR8PPxdrIkVKZpe', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 0, 'system', CURRENT_TIMESTAMP, 'kXTpdYpb6QOrw4qXxS3JtxlPu9qtBnqW', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 1, 'system', CURRENT_TIMESTAMP, 'FLFzkJTFLeF5sUoYVqXQOX7TpA0kDFrX', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 2, 'system', CURRENT_TIMESTAMP, 'U1gGAwvAd5xFc6Q3duVLnD3Xk67A2hwi', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 3, 'system', CURRENT_TIMESTAMP, 'q48SiQ5qA2skKEo0MMXcxRo15QyeThZS', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 4, 'system', CURRENT_TIMESTAMP, '9wYJqqb1bqdHPLjSRe0ORKCyVm2Rs6Sd', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 5, 'system', CURRENT_TIMESTAMP, 'iSvgDATWuJhtvIkSQZpJd5fqWUbaakSf', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 6, 'system', CURRENT_TIMESTAMP, 't1v3fEtcK06g9HJHPiddfMwdcjt1zaYO', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 7, 'system', CURRENT_TIMESTAMP, 'iTULJqTIfevDY9MLhaY9Q5Tc1SiyTLcs', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 8, 'system', CURRENT_TIMESTAMP, 'v0mrneTxgsqO5FHoUsov8XYEGcqpZuAp', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 9, 'system', CURRENT_TIMESTAMP, 'CpSFA0YcWWtPq82phHufivopi9SNS3CF', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 10, 'system', CURRENT_TIMESTAMP, 'lpX58WnBCmIDr44ahMvtwviWfu5178o5', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 11, 'system', CURRENT_TIMESTAMP, 'WWNlSVbZorstup7M474PqIfD6tMolLPF', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 12, 'system', CURRENT_TIMESTAMP, 'NcL6XVGP23lqS2QUA7IstHs2UXh42jP1', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 13, 'system', CURRENT_TIMESTAMP, 'U3I8fi4NwzXAfme7Gd4sxLLHbwi0cyyD', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 14, 'system', CURRENT_TIMESTAMP, '6u7JJc0jmb1m6gHjDXAU4kElKfu7744N', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 1, 15, 'system', CURRENT_TIMESTAMP, 'ZXP6LddVtCzSYj4rq5UfiYHG1kcXE0YB', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 0, 'system', CURRENT_TIMESTAMP, '9JgxoQfzJmBmcGd8fHtqiHl8oCHl650G', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 1, 'system', CURRENT_TIMESTAMP, '1veRmnIVspOYde3pAm5q8aFQKZzg1Nko', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 2, 'system', CURRENT_TIMESTAMP, 'EzJwmc43QW3dNeDdh7n0unwyJkksOxk2', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 3, 'system', CURRENT_TIMESTAMP, 'fgxXQjl41g2OZO6a9mMc2GDz2soE1C9B', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 4, 'system', CURRENT_TIMESTAMP, 'g1dJJZPq1xLub8VsbHpQzZ6l0jNYWhfB', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 5, 'system', CURRENT_TIMESTAMP, '0x3LF9NBJLPpEKq9onH90zHgEiwrK2jg', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 6, 'system', CURRENT_TIMESTAMP, 'pYl7NF22pQeGua79UzEd373ZRumOJp5Q', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 7, 'system', CURRENT_TIMESTAMP, 'claWifC8bh6WvxZclSDqCvmzvZDUoZoi', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 8, 'system', CURRENT_TIMESTAMP, '4uRcGxMG5Tx3qt2MGeAOo1MdW0YiVdNo', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 9, 'system', CURRENT_TIMESTAMP, 'EOslpxM0zIPHGnlfOatoe0vkQZhBMpaM', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 10, 'system', CURRENT_TIMESTAMP, 'mjehKDxN9zeTnMk0nBtXlIaMq7wZGfqo', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 11, 'system', CURRENT_TIMESTAMP, 'CnKa9TIIChw8f318ne0rOxHvpwacoo7Z', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 12, 'system', CURRENT_TIMESTAMP, 'lTDL3hYcVqO2L0g6OolemW5Z5MdYRRNt', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 13, 'system', CURRENT_TIMESTAMP, 'STHI3jPUcuHDvv9Q6eew1xFjYUoiITMx', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 14, 'system', CURRENT_TIMESTAMP, 'bxgC7TCBIo5Sft8etMnk4w3fJf2b2hOC', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 2, 15, 'system', CURRENT_TIMESTAMP, 'qwSNc67IqCtL3Hf4jFy534tiBISq0Htf', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 0, 'system', CURRENT_TIMESTAMP, '4EyCntKy78Z1Plqmi5Y7gNpfadjaue4J', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 1, 'system', CURRENT_TIMESTAMP, 'YOAdLtsoXeC6S2xUbs3yMmFF5QF7f3Ek', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 2, 'system', CURRENT_TIMESTAMP, 'uHu8O3CDPsg3wzY4WmaMQW6KdrLj4leT', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 3, 'system', CURRENT_TIMESTAMP, 'WllFbpQdyyiZ1svaGNQRCJrdPrNXpIxS', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 4, 'system', CURRENT_TIMESTAMP, '8AStC1WPQL30AKjonCft17xmI8cH0Vgm', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 5, 'system', CURRENT_TIMESTAMP, 'kxj1EdSXMGA8UePBMi0ZZBtm4HndcfmG', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 6, 'system', CURRENT_TIMESTAMP, 'eauSpjey5ThIitB8Fs8npTR62Yts4BrI', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 7, 'system', CURRENT_TIMESTAMP, 'PtfHjVTS2vcDaqK56Xdx9royireaPFuv', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 8, 'system', CURRENT_TIMESTAMP, 'A2DrPAtiIF00uPVKRwDqZHb7H3N69gp6', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 9, 'system', CURRENT_TIMESTAMP, 'W1aPeLdXWipufyVktt6yB4bDD4mJ3d6N', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 10, 'system', CURRENT_TIMESTAMP, '4GE0YUWJCL57PUNcYKceIsWsb7dFTQlG', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 11, 'system', CURRENT_TIMESTAMP, 'jIhQuEp9u1aUxxvoI0WG7JKhfvnRQOW6', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 12, 'system', CURRENT_TIMESTAMP, 'VV2UNd57GyZq2BGc9qgR2mY2pM5WBjWk', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 13, 'system', CURRENT_TIMESTAMP, 'cuxrr8dK8vxQMxqQkE0hw5geKt2l1HWc', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 14, 'system', CURRENT_TIMESTAMP, 'p3S7xDQNTN1wHgzQl7f3sCTFD9hzH3gh', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 3, 15, 'system', CURRENT_TIMESTAMP, 'SPAsXBIRxipal6UTKJ7wFjWhjnqIHqIy', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 0, 'system', CURRENT_TIMESTAMP, 'uV3viVAjqhhKPKSKceIIlkFNpxuHdGBo', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 1, 'system', CURRENT_TIMESTAMP, 'VFaH987xH2VXWurqKJisZXrivaOjNgfp', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 2, 'system', CURRENT_TIMESTAMP, 'QYZlFQorRG4yBq6DW3jAXnSHPwHCAew6', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 3, 'system', CURRENT_TIMESTAMP, 'vh7f0L9ghM64GzLq6yiMzyYpBA2rsybY', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 4, 'system', CURRENT_TIMESTAMP, 'dtmLmER3nCgvVOS34WMCPTbr7Pi39gR2', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 5, 'system', CURRENT_TIMESTAMP, 'rrLndDpAJjHSUWHHy3F63p4gggcVenPV', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 6, 'system', CURRENT_TIMESTAMP, 'EjgLTiFitLwxn2Ubxaf4sgLxqZFZIIw8', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 7, 'system', CURRENT_TIMESTAMP, 'zWAPbRhTkHv4BAsL2Z5WRcqROdbAGOWL', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 8, 'system', CURRENT_TIMESTAMP, 'xFa30uaVMtXRph3ZbuDPtA00IjmiRnjK', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 9, 'system', CURRENT_TIMESTAMP, 'RoFjUKHuu7VlCFexSkpxZfgip2Fz9XB0', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 10, 'system', CURRENT_TIMESTAMP, 'WUbpFHJMKIZmGb8zTsbOXuPfkAFFHj5J', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 11, 'system', CURRENT_TIMESTAMP, 'r6P73ucBNic7YT4dAPIluM38j68jYpra', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 12, 'system', CURRENT_TIMESTAMP, 'jnPpvnvmM1luHWvx7NeO6QkgLouAXR20', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 13, 'system', CURRENT_TIMESTAMP, '5D7URCkLhROl1eFtnpUUmjJyUr24JKJO', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 14, 'system', CURRENT_TIMESTAMP, '7mZAiGtXHSnNHoLqnFjVKtFNFo2fKZjy', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 4, 15, 'system', CURRENT_TIMESTAMP, 'BVRC7JYz0qZmnQnRach227J6bfRR1thF', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 0, 'system', CURRENT_TIMESTAMP, '5bHzSmxW2ucnyueeA1Z0Ae4FI8R93ifT', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 1, 'system', CURRENT_TIMESTAMP, 'SisuE5tgaUrQtptHObgzw13bGViNrpWG', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 2, 'system', CURRENT_TIMESTAMP, 'YZ47NjwfNHRzdQPPTLOT0VJBcnNLNxTc', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 3, 'system', CURRENT_TIMESTAMP, 'wipMTBZfGuN4oB2qdqTWoNN7LYAMuvXt', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 4, 'system', CURRENT_TIMESTAMP, 'RzPkVN9gUgHzl8a9WfNcRDUkEQqj9N9C', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 5, 'system', CURRENT_TIMESTAMP, 'sjqwxCCpWbWbXd7wsR8g37hBpZeRVUwo', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 6, 'system', CURRENT_TIMESTAMP, 'VJxH6rtXwdKjROoKt1v3IKFhQSFlyCgu', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 7, 'system', CURRENT_TIMESTAMP, 'qLY0ZDqqmoh3nSLIH6eELp1WGxRLrTou', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 8, 'system', CURRENT_TIMESTAMP, 'NSv6fEdl2puNduLyBudDtwAPiFBYh7Pp', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 9, 'system', CURRENT_TIMESTAMP, '5FWFrzDp6GdvjsjwXmeYTnKqEhqN0M1W', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 10, 'system', CURRENT_TIMESTAMP, '2ENZ7YluXQuy2MPM5gx679ffQFiJcxAe', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 11, 'system', CURRENT_TIMESTAMP, 'mx9imR5FmPAPk6LmOLDgiRpUu7A1wEvn', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 12, 'system', CURRENT_TIMESTAMP, 'auUP1kIrmPezsG86SdqmBcVMZupyuA1b', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 13, 'system', CURRENT_TIMESTAMP, 'eeq6IQRLuSXX9M69yGehyUt052LgSDbb', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 14, 'system', CURRENT_TIMESTAMP, 'ijnUoFPolDRpD0sJUUiAMUPNEqCY3dwh', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 5, 15, 'system', CURRENT_TIMESTAMP, 'kXo61CJ2Ghzk1rq9RbBrWsFLw564QeS0', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 0, 'system', CURRENT_TIMESTAMP, 'GiUGvzo9gSeTVkFXM7Yzy0M5xljP3GGF', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 1, 'system', CURRENT_TIMESTAMP, 'p6aU8AOKzv78x5TdJt2NtIXCskCCm7um', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 2, 'system', CURRENT_TIMESTAMP, 'xduQe6cnctaRVKqdGTX1hmwNYWpK1kuK', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 3, 'system', CURRENT_TIMESTAMP, 'KuYcJxJOSiYlIzdNBer5NwzfMdRIbNHy', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 4, 'system', CURRENT_TIMESTAMP, 'ZyLWqafCKZHRESmR64w1OUL9eRJseBh6', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 5, 'system', CURRENT_TIMESTAMP, 'OLHNBl0oxqxJpl9wa9Eje7CuHeYt1fwq', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 6, 'system', CURRENT_TIMESTAMP, 'wnJeWbDhYDlSY6poOZpqB0EJnLRkBUaj', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 7, 'system', CURRENT_TIMESTAMP, 'vkDXJRcAER9LmanZjZySL8lNafI56daI', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 8, 'system', CURRENT_TIMESTAMP, '20UiKktiHSfoxU7jQYs0SbEobT0DRzrx', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 9, 'system', CURRENT_TIMESTAMP, 'WFTkDarUaFup9Wncl7h7k3mtHKhfjtRn', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 10, 'system', CURRENT_TIMESTAMP, 'k9sJLrOu7szZpG4aXc7hjF0MBKxPfkEu', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 11, 'system', CURRENT_TIMESTAMP, 'AjqaaRPNgUPtyKLAhkX4DnMXzlOgU35I', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 12, 'system', CURRENT_TIMESTAMP, 'lpIjxcMUQW13OTz17YwBxcMo50svN6Uh', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 13, 'system', CURRENT_TIMESTAMP, 'lcwflITt8gFYmF86BvIls61EugDSmHL8', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 14, 'system', CURRENT_TIMESTAMP, '19dzsP9dEr2l7923gQS8MG11qvnpl3E3', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 6, 15, 'system', CURRENT_TIMESTAMP, '2mrtsIrIRnFFGOe1x7lhpMccEMLj9i2G', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 0, 'system', CURRENT_TIMESTAMP, 'eo5sKWGD1kkoGs26zUVqjeNwjmLewU9s', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 1, 'system', CURRENT_TIMESTAMP, 'VEo0IoAZPGNFoHMI5mVwKtp9WnO77SZX', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 2, 'system', CURRENT_TIMESTAMP, 'hZbZeyrDLjsjRyUqm8ri8yz6Ogsidg2H', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 3, 'system', CURRENT_TIMESTAMP, 'OP2YdWU7OyvUIZg8bDtxftk98959KFu8', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 4, 'system', CURRENT_TIMESTAMP, 'YS2Kn3MP89e3BPKGznDDts9gFG8Q6xKL', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 5, 'system', CURRENT_TIMESTAMP, 'C3SIB8SrwTbTIOqpCa3ImjzTUioIuoRb', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 6, 'system', CURRENT_TIMESTAMP, 'FWIkX5jyMhPZKerEQkvEiuf927OY7MUc', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 7, 'system', CURRENT_TIMESTAMP, 'lv5hfNbSwaJiYhvPjwaen3CzdQTVyufU', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 8, 'system', CURRENT_TIMESTAMP, 'hvw0CvcxPDGaDH5Wga2sFbpyvkpZQn7z', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 9, 'system', CURRENT_TIMESTAMP, 'uxrKXpptd4sZQCoHOlQYBanaJlE1VRic', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 10, 'system', CURRENT_TIMESTAMP, 'cLTQkHVogQDWBaE0d9wcWGBW65ug5j5q', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 11, 'system', CURRENT_TIMESTAMP, 'MWjxymHJugZRtDpdQk4KDqqeKCaT8ncv', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 12, 'system', CURRENT_TIMESTAMP, 'cuxbCDsZzWBS12cA8rvS5F64W9mRzm4b', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 13, 'system', CURRENT_TIMESTAMP, 'deZPg1LtOuoCehJf4OacAQlef4xwyphF', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 14, 'system', CURRENT_TIMESTAMP, '1gqiPmQHtLVEkTzf9ibP0fv7pWtPaZLL', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 7, 15, 'system', CURRENT_TIMESTAMP, 'qmVLSwrhRIXtRga5I4t6QydZyyhdFkqT', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 0, 'system', CURRENT_TIMESTAMP, 'vpw8CyGQFchwm6PdagFVy29JKJDWJjWu', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 1, 'system', CURRENT_TIMESTAMP, 'u2Zu4PEbMEyYSVzPLvsLCJOmAzst1AkH', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 2, 'system', CURRENT_TIMESTAMP, 'qKXpKhEJf1JznDUZRnhDO37ZvRuoaz9b', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 3, 'system', CURRENT_TIMESTAMP, '6SGUm2VZdC8CGLGbRXDtgPsLbQjiBeKh', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 4, 'system', CURRENT_TIMESTAMP, 'gek19FgxvxYP6Rajn8a3gsC3SiEv7sxg', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 5, 'system', CURRENT_TIMESTAMP, 'rarXXXPtXQ1s2S0igSBkO0icCmydfQpb', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 6, 'system', CURRENT_TIMESTAMP, 'pPGwVMXTsDFQ49K2Jtbdj7GUcUTfEFd4', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 7, 'system', CURRENT_TIMESTAMP, 's7HSvxrY9RBXue9dXZkzPNSnL1EKYaNn', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 8, 'system', CURRENT_TIMESTAMP, 'IUBRJxmaEXKx9bK6ZjwjSpKdYMGbjz4u', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 9, 'system', CURRENT_TIMESTAMP, 'dZLmbbK46Nx33RuEub2LPFKnERQI3Fml', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 10, 'system', CURRENT_TIMESTAMP, 'KlUV0orKyzsyvkMA8CBIMQ0jw7WQkuTv', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 11, 'system', CURRENT_TIMESTAMP, 'EJFAY1wHfNVMFgOx4LFfgAXhmf3THhf5', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 12, 'system', CURRENT_TIMESTAMP, 'MbG46xHvi5SYEH6avMYppst9xCQwrdgt', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 13, 'system', CURRENT_TIMESTAMP, 'fu3mNSemIrXyZFiR35l2MkFvajtIRvwc', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 14, 'system', CURRENT_TIMESTAMP, '1Fl7Iz1lIeOA7qHzE4Jjr3z9KxvguUfh', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 8, 15, 'system', CURRENT_TIMESTAMP, 'VmA9jx6vNn0ZDUv45OsMTtNR70ofZ3ZY', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 0, 'system', CURRENT_TIMESTAMP, 'FlPir1icB7wGVKbgWSADddrPKQhMl9wr', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 1, 'system', CURRENT_TIMESTAMP, 'EnuyGEt8QhsPYRrIJHtpsoYEmyms4uPW', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 2, 'system', CURRENT_TIMESTAMP, 'xMG4zMp0gk4bcXQwm9NxHZ8P0sZJPU80', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 3, 'system', CURRENT_TIMESTAMP, 'dQxhz6vt5rVsxKgOU0kjOKbIfbTJclUl', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 4, 'system', CURRENT_TIMESTAMP, 'lJ2sydFJ3XAlq0dkAkwiKIkKMZXLHcm3', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 5, 'system', CURRENT_TIMESTAMP, 'EKqGLEraNNuH3u7fDZOFPew2oUKmui3o', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 6, 'system', CURRENT_TIMESTAMP, '5vv7TON0LajklFTSE1Qxy36tjZSyy1Rq', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 7, 'system', CURRENT_TIMESTAMP, 'ix2edpvVn6TArz20FdF39tiBxOjbI0ND', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 8, 'system', CURRENT_TIMESTAMP, 'gIGYHc5LeBGvgq97jqV3HvjIbBrpEYbK', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 9, 'system', CURRENT_TIMESTAMP, 'CO35BWdxToZEu9ATbxNL6YYIru6j8Uq2', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 10, 'system', CURRENT_TIMESTAMP, 'OJ7PJyBoYBq1cvbFueiw6naolHWz5Mz9', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 11, 'system', CURRENT_TIMESTAMP, 'inved2M0AWynxEoC8w0JovLQQ4fS0KJo', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 12, 'system', CURRENT_TIMESTAMP, 'g0o6lknYhCRIvm4ex1WuRTxDVml5BBvN', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 13, 'system', CURRENT_TIMESTAMP, 'vQL5S1H5YbCdQH4qK4faarK0a02s1eMF', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 14, 'system', CURRENT_TIMESTAMP, 'oZbtNoRdPckEy0yxUxB2bOfl7H4IYZmM', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 9, 15, 'system', CURRENT_TIMESTAMP, 'joCrduXuHZRVK5Z3JNuU437XBQdIlOR7', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 0, 'system', CURRENT_TIMESTAMP, 'IX0qZC2Zrg9aXgxs7JKAGphJVS7ULJKn', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 1, 'system', CURRENT_TIMESTAMP, 'O6rCDiiKDL4RI6BSR66dWOePOuDJIb2m', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 2, 'system', CURRENT_TIMESTAMP, 'N0kyfOcSRGNPgE9fZUSR2xQKT9mlzc8e', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 3, 'system', CURRENT_TIMESTAMP, 'zANrbBOf85Eyv6viuuHwFzceh0x9pz7b', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 4, 'system', CURRENT_TIMESTAMP, 'l5oWFZvlCdYdvp55ZkvRx1hfJqQYvhsI', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 5, 'system', CURRENT_TIMESTAMP, 'B6tCG7H696EwTHDrHhmzIbD7AUH7WLYF', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 6, 'system', CURRENT_TIMESTAMP, 'YtAlUcA7WJD24pFJEZcgYYV6dT0HgLiD', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 7, 'system', CURRENT_TIMESTAMP, 'YTq4XfCfwf4uHUWsG9PRLliFN4eC3JBj', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 8, 'system', CURRENT_TIMESTAMP, 'npqhoey2B8m1kki9ndft9ncJ5bn5Wpse', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 9, 'system', CURRENT_TIMESTAMP, 'dScdJuzJQRyHFq8tKjmnkq9LFDkouG0y', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 10, 'system', CURRENT_TIMESTAMP, 'UNFYfS3yKGm6Rv4wfKAXEXC5XYp6kW1f', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 11, 'system', CURRENT_TIMESTAMP, 'hxRk7DpgptqlpvllPWN0WSI7WaIaILJK', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 12, 'system', CURRENT_TIMESTAMP, 'Auyfv6lNZiNuqyf8XKiSmp6vjFB2OwLX', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 13, 'system', CURRENT_TIMESTAMP, 'AlAxmG4vCox6Ieh5mOQKAQQbGtNXliYJ', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 14, 'system', CURRENT_TIMESTAMP, 'XOKrG66ELjBU1cwvMxZPLNL9ZRIWUAvC', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 10, 15, 'system', CURRENT_TIMESTAMP, 'h8YL2h1Su3sTwoB26kVmyZ7uCJ4xG2Su', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 0, 'system', CURRENT_TIMESTAMP, 'dVIycV3cob3ULtdkWUOpMh9Iv5OPMmVL', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 1, 'system', CURRENT_TIMESTAMP, 'rC7pKfBHc2n0dzw1kq4I60qDfjJjSoOE', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 2, 'system', CURRENT_TIMESTAMP, '0oU5BnytnXl4tvqaKwpfIWmsqFp00uOL', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 3, 'system', CURRENT_TIMESTAMP, 'Dlhud4JkZH0ZwfRoWhLhAc6ydq7WbDXW', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 4, 'system', CURRENT_TIMESTAMP, 'HD2oQgB10dMWdGQ2lwumsMuQAWbkYjx9', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 5, 'system', CURRENT_TIMESTAMP, 'mvc4nj2fQpMuVvd5hexrKaj2BZmkhxX3', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 6, 'system', CURRENT_TIMESTAMP, 'aGxRHkt7SQ3YUJBKwfpHyOHZrJp4fGZt', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 7, 'system', CURRENT_TIMESTAMP, '3t2sXtAARG76zisGX0K3J0PR9P5yntys', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 8, 'system', CURRENT_TIMESTAMP, 'qTA5CvZJE4YKhWT6zwAKjoxpD9tzYXse', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 9, 'system', CURRENT_TIMESTAMP, 'ktslHWdJB7lIZq8vrjGypr3WcJQHgB4t', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 10, 'system', CURRENT_TIMESTAMP, 'K5q7QsXybRz3jjvhAbaFVF1fYVLuqOUg', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 11, 'system', CURRENT_TIMESTAMP, 'HkBFIcpm56zRDe7fMl1uT8xBUinOjbnd', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 12, 'system', CURRENT_TIMESTAMP, 'ZiDaraO88kEMMBMJdX6Ki9HlXNY1xCDO', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 13, 'system', CURRENT_TIMESTAMP, 'o8sLoeUiZfcK0J94NbIjUBKwEKdNVScN', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 14, 'system', CURRENT_TIMESTAMP, '39ktWdQb4fH3sFSxrIugZyOPEMFOI8Ax', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 11, 15, 'system', CURRENT_TIMESTAMP, 'Qfe8HPjavzCmq0zaJE0Mame14SIOb5Iy', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 0, 'system', CURRENT_TIMESTAMP, 'KDttZhPKIvJgFdOtG5SEZ1PShQO5P21w', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 1, 'system', CURRENT_TIMESTAMP, 'dFOC2xCsHwsWsLSGZJJkwXHLhLvzhpgp', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 2, 'system', CURRENT_TIMESTAMP, 'jSZYfalO5Rs23cvLb0LH3fU3jofnxSgP', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 3, 'system', CURRENT_TIMESTAMP, 'UrUn5Qd60MzeX8pCH5XEyQLVxLbjvF71', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 4, 'system', CURRENT_TIMESTAMP, 'VMP03AVnJ1zC6HMoHMRdCaY2lRTfKno1', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 5, 'system', CURRENT_TIMESTAMP, '0XzHahusIlZDYhKuir3c7QCFZLOL6Sfi', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 6, 'system', CURRENT_TIMESTAMP, 'EP1wweGJzU7IWHxgsxH57lBiNtf6y00F', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 7, 'system', CURRENT_TIMESTAMP, 'Yy2bEdp2NeJ3UQiAUeaxYQtWyRHojrMN', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 8, 'system', CURRENT_TIMESTAMP, 'n0KxQt5hVujE5JWXfmCN4laeO7FwmtvB', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 9, 'system', CURRENT_TIMESTAMP, 'clSq2DJAdPCbud1QRquGWl3WBuxARrlF', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 10, 'system', CURRENT_TIMESTAMP, 'veblCZBrlTuvVhDWwxp8vFPNYDintAEg', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 11, 'system', CURRENT_TIMESTAMP, 'YjpiMNYvGW8YZOoNxFkmxoCz70TaTUVO', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 12, 'system', CURRENT_TIMESTAMP, 'Ba60EBgPGZp6LGCsiCiOxIv5wR34EfbT', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 13, 'system', CURRENT_TIMESTAMP, 'kKJaoKmMoggIFUtyXqmYsmP1LHItQat7', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 14, 'system', CURRENT_TIMESTAMP, '1UDdWSd0dgPI0LyEKpdbZcN5i5Q7R1PX', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 12, 15, 'system', CURRENT_TIMESTAMP, 'sJF7Q3NEad8llqFbw6caYINRwzKiUUX4', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 0, 'system', CURRENT_TIMESTAMP, 'WO99qtCVSosSfiI16QiSl6n3CZEf3oom', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 1, 'system', CURRENT_TIMESTAMP, 'nKWbESZ4YVWb75hAOkacSHojMtJhETyE', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 2, 'system', CURRENT_TIMESTAMP, 'Y8C1BfhXJpy0ReyGdL4lYgP12y6y0JDb', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 3, 'system', CURRENT_TIMESTAMP, 'T6H4EP4DL53uOFhLv92liSZU7xMoHW20', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 4, 'system', CURRENT_TIMESTAMP, 'LKCXVC7xSxzlQ9kH5fjJZJyTY6KALcLi', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 5, 'system', CURRENT_TIMESTAMP, 'kQRV6ZIEZaIFq9IC7BX1cwmWh2cjZ6jD', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 6, 'system', CURRENT_TIMESTAMP, 'hLKbgWQDMVxRmXrBUqfgYZCdctmubdnC', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 7, 'system', CURRENT_TIMESTAMP, 'PfePjEILqFpQjzyELHdP6QHNAcVxFwS2', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 8, 'system', CURRENT_TIMESTAMP, 'd7NTSv9qQvu1J5koYSt7HrIjTDzhAGRG', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 9, 'system', CURRENT_TIMESTAMP, '2XvLEpqIGTzn8izrFgUxUlprwB5FTa8I', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 10, 'system', CURRENT_TIMESTAMP, 'HgyAsXdg3gd2Q3uL5LyTlutxfpfi1bRn', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 11, 'system', CURRENT_TIMESTAMP, 'ZKsra0J2R9g1Yn8p8B0EBc7iHUbbSgRh', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 12, 'system', CURRENT_TIMESTAMP, '7l6g6LC88A0B99LldBi7Xwyq3wdcXBh2', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 13, 'system', CURRENT_TIMESTAMP, 'reyuw4WW09ZTX96DBwxyti3n1f63lHvG', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 14, 'system', CURRENT_TIMESTAMP, '2WIV7jj9JQ8TMSPbyJC5ewYo2Rht36Yw', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 13, 15, 'system', CURRENT_TIMESTAMP, 'enq8Q84UjFQSvauV2LKSjLntsmNbmAHR', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 0, 'system', CURRENT_TIMESTAMP, 'IWke2JVEh3Tfcn3R4Zyl6pzuPqznxbkR', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 1, 'system', CURRENT_TIMESTAMP, 'w6Amlow4MHAbHZfcS7wrXYBaxj7SUUYP', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 2, 'system', CURRENT_TIMESTAMP, 'xBNynQSbDB3OO6k08m2HM0MOksMtrQKE', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 3, 'system', CURRENT_TIMESTAMP, 'YbNs9IjdzN0iF51TD8Fh6spix5P4Wppu', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 4, 'system', CURRENT_TIMESTAMP, 'hrORKpYflyHWzdq6cCMYv1UkVxcMAt2J', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 5, 'system', CURRENT_TIMESTAMP, 'bCDLqbutwZm55Y1hy08aiEzGDyheGRBi', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 6, 'system', CURRENT_TIMESTAMP, 'U23bXcGbnTHjuMtYhEYl7829lilB3lCX', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 7, 'system', CURRENT_TIMESTAMP, '6NIksGOB706ExQL4w3wmQYMZQIsE89Td', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 8, 'system', CURRENT_TIMESTAMP, 'nnEmahx43GR0z1BuduOANEQvlo6ny2zd', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 9, 'system', CURRENT_TIMESTAMP, 'h4YddSlxfG82NsdscacYMkTeneM8g6xT', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 10, 'system', CURRENT_TIMESTAMP, 'VooNsrzjm1Yaka3952i4WpSjKgC1DhIt', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 11, 'system', CURRENT_TIMESTAMP, 'McXW50ne8N0TUPiXQa25De402iKY0Shq', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 12, 'system', CURRENT_TIMESTAMP, 'jXAvgHZigHL7HnWlzyXQUzYGuYttmfSg', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 13, 'system', CURRENT_TIMESTAMP, '3UkLrGPT3ctJpyuV3nyZSB0CrlrsH9Q4', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 14, 'system', CURRENT_TIMESTAMP, 'vvTMMsiRelwYZIgu1iF9ZZSCis2mqOrA', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 14, 15, 'system', CURRENT_TIMESTAMP, 'H5osEuICpXI6U2lZs2Gngohwaosh6TIm', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 0, 'system', CURRENT_TIMESTAMP, '5P4iB59cbueGa7QaiZriTAmQxuyjWpvi', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 1, 'system', CURRENT_TIMESTAMP, 'nYzKQEGYJENAKKWPN3tuTmQhOpklOt21', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 2, 'system', CURRENT_TIMESTAMP, 'pKYIWdbLeG5wCIVhj5GVGVD6V13WVGrH', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 3, 'system', CURRENT_TIMESTAMP, 'ePTb1TcqBkq6ZSqgf32JOYTURQ8J3LLK', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 4, 'system', CURRENT_TIMESTAMP, '7EGjD2iKmJOgrBTHiFRTJjCisV8YkPYF', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 5, 'system', CURRENT_TIMESTAMP, 'Awr83Ndcfyl4Ektx7XZy5WBUio9lCO1f', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 6, 'system', CURRENT_TIMESTAMP, 'OMHVNcfFSE9o2d6GJ9ictzyDf1FIYQei', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 7, 'system', CURRENT_TIMESTAMP, 'QM45GAkQEq1s3QOXhqEQEgx3Tw1ttinp', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 8, 'system', CURRENT_TIMESTAMP, 'Awm001x8knDo1TJh5TLXQhkRpyYbkiC8', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 9, 'system', CURRENT_TIMESTAMP, 'njF6sR8g7smMKVzpJLbYunW1P2hKTFIm', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 10, 'system', CURRENT_TIMESTAMP, 'WgBwwjRu08ndDp48xfb78jvu2Ek2M7BB', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 11, 'system', CURRENT_TIMESTAMP, 'tRpH9uLo75OR7indLtOCjHXLIwyjs4yT', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 12, 'system', CURRENT_TIMESTAMP, 'ko0B2E6emD9VrSO7gt9J51n7sY9gVWe0', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 13, 'system', CURRENT_TIMESTAMP, 'MkVdtGs9zOuo6IKlpdmWw0IWIMSpE37s', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 14, 'system', CURRENT_TIMESTAMP, 'CEjUQlkIEhjlqf4t7HM8VdWRcuxWIxrR', 'ivkegen12345', '');
INSERT INTO SEC_METRIC_INFO (MAJOR_VER, MINOR_VER, ROW_NUM, COL_NUM, AUDIT_ID, AUDIT_DTM, ENC_VAL_CTT, IV_VAL, ADD_TXT_VAL)
VALUES (0, 1, 15, 15, 'system', CURRENT_TIMESTAMP, 'gAwTDJNheqcpzT4J4b3EpOnwlRq0yP6g', 'ivkegen12345', '');